vich_uploader:
    db_driver: orm
    mappings:
        cake_picture:
            uri_prefix: /uploads/images/photo
            upload_destination: '%kernel.project_dir%/public/uploads/images/photo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer